### ISSUE TITLE
Current draw? Single LiPo and RGB led

### ISSUE THREAD

**Issue by kirkyb** [Protonerd/FX-SaberOS#9] opened 2017-10-22 11:50 UTC
I've recreated figure 13 from the Stardust user manual using +ve straight to blue and green led and resistor to red. The board functions perfectly fine with the RGB disconnected but crashes out when it is connected and 'ignited'.
I've tried to reduce the brightness in the Arduino code (i.e. to reduce current draw) but this doesn't appear to affect the RGB led brightness. Is there any other setting that can be altered?

**Comment by jbkuma** [comment] 2017-10-22 15:01
What size battery are you using? It probably shouldn't be drawing more than
3amps.  Are you using resistors?

On Oct 22, 2017 7:50 AM, "kirkyb" <notifications@github.com> wrote:

I've recreated figure 13 from the Stardust user manual using +ve straight
to blue and green led and resistor to red. The board functions perfectly
fine with the RGB disconnected but crashes out when it is connected and
'ignited'.
I've tried to reduce the brightness in the Arduino code (i.e. to reduce
current draw) but this doesn't appear to affect the RGB led brightness. Is
there any other setting that can be altered?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Protonerd/FX-SaberOS/issues/9>, or mute the thread

**Comment by kirkyb** [comment] 2017-10-22 15:29
I'm running everything from a single 18650. Using 3.3ohm 2w resistor on red channel to drop from 3.7v to 2.8v (as specified) and running straight from +ve for blue and green

**Comment by Protonerd** [comment] 2017-10-22 15:50
What do you mean by +ve? I would connect one LED at a time and see which one causes the problem. Provided all the connections are right.
BTW, the Figure 13 I just realized can be misleading. The red connection which is suposed to show how to connect BAT+ to 5V might be interpreted as connecting all 4 signals together. I hope you did not do this.

**Comment by Protonerd** [comment] 2017-10-22 15:57
I will upload a new UM version

**Comment by kirkyb** [comment] 2017-10-22 16:00
Hi Andras, first of all thanks for the replacement board. I'm powering the blue and green led straight from positive of the battery and the red I'm using a 2w resistor in series. No, thankfully i realised that it is only the 2 signals and not all 4

**Comment by Protonerd** [comment] 2017-10-22 16:04
Worst case you bricked one of the transistors, that can happen quite easily if you make measurements while powering the LEDs and accidentally shorting an LED, which will send the whole current through the transistor, killing it. That is why I would go on the LS pins one by one seeing which is reacts strangely.

**Comment by kirkyb** [comment] 2017-10-22 16:18
R, G and B ask light individually without issue. Ignition seems to work fine but its the clash that actaully crashes the board. Just tried cycling through the menu and the board becomes unresponsive when it reaches clash colour.

**Comment by Protonerd** [comment] 2017-10-22 16:31
What type of battery are you using? The default for the color mix is white for a virgin board. Maybe not the best choice as it will active all LEDs and might trip the current protection of your battery. Do you have a protected battery?

**Comment by kirkyb** [comment] 2017-10-22 16:47
Its an ultrafire 18650 and yes its protected. Could i change the default color then if this is the possible issue?

**Comment by Protonerd** [comment] 2017-10-23 11:06
You can change in the FX-SaberOS.ino, line 197 change
if (!loadConfig()) {
to
if (true) {

and change the values in lines 209 - 217 all to 0.

Then try, if works, change back the line 197 to its original.

But they all have values of 20, a very low PWM value, so no real current should flow. I'm surprised. I would recommend to only connect one color at a time and try all functionalities. This way you might even change the colors in the config without changing the code.

**Comment by kirkyb** [comment] 2017-10-24 21:38
I've tried your suggestion but that didn't work.
But....
...tonight I used my 18650 battery for a pumpkin prop at my sons halloween party and upon plugging the battery back into the stardust I've noticed that in the menu it now says battery 'nominal' and not 'full'.
The system is much more stable, the LED illuminates with all blade functionality and i can cycle through the full menu without crashing.

**Comment by Protonerd** [comment] 2017-10-28 11:40
Hi Kirk, do I read it right, does the saber work now? I have no clue about the erronous behaviour with the fully charged battery to be honest, but if you have new findings to shed some light on it, let us know.

**Comment by kirkyb** [comment] 2017-10-28 12:38
Hi Andras,

The battery issue hasn't returned thankfully. A strange one really but i
guess it has something to do with its protection.
I swapped out the red LED resistor too for one with a higher power rating
and it was still giving me issues. I've since decided to omit this LED and
stick with only blue and green, it works perfectly. I can now increase
brightness to 255 for the remaining LEDs.

I aim to dismantle my stunt saber tonight and proceed with the install.
Have you any experience removing hot glue from the inside where the button
is?

Also, I've finally had the chance to try out the saber font that i
reproduced for the Stardust, it appears to work very well so far!

Kirk

**Comment by Protonerd** [comment] 2017-10-30 13:48
Glad to hear that. I still think that if the 3rd LED does not work it might be due to a bricked transistor.

**Comment by kirkyb** [comment] 2017-11-06 13:42
Just returning to this issue. A gut feeling told me to try using the v1.1 update with a second RGB LED that I owned (same supplier). Now I dont know if it was a faulty LED previously or whether its because of the new code, but I now have red working perfectly!

I have only had a sound distortion issue twice since installing the RGB but a quick charge overcame this.

I will monitor closely whilst draining some of the battery and will close the issue if all is well.

**Comment by jbkuma** [comment] 2017-11-06 14:30
Glad to hear you've got it sorted.

Sound distortion can be caused by a low battery for any saber board. The
sag effect, a voltage drop under load, can make this worse especially if
the battery isn't properly designed for high current.  The fact that
charging ameliorates the effect is the surest sign.

As to the LED issue, it's a head scratched based on your description. Could
be an odd issue or out of spec, it's hard to tell b from here.

On Nov 6, 2017 8:42 AM, "kirkyb" <notifications@github.com> wrote:

Just returning to this issue. A gut feeling told me to try using the v1.1
update with a second RGB LED that I owned (same supplier). Now I dont know
if it was a faulty LED previously or whether its because of the new code,
but I now have red working perfectly!

I have only had a sound distortion issue twice since installing the RGB but
a quick charge overcame this.

I will monitor closely whilst draining some of the battery and will close
the issue if all is well.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Protonerd/FX-SaberOS/issues/9#issuecomment-342151923>,
or mute the thread

**Comment by Protonerd** [comment] 2017-11-14 09:28
Closing as it looks to be solved.

**Closed by Protonerd** 2017-11-14 09:28 UTC
